### ISSUE TITLE
Is this plugin can be used with unity educational for research?

### ISSUE THREAD

**Issue by luvwinnie** [styly-dev/EnterpriseCameraAccessPlugin#7]

**Comment by from2001** [comment]
@luvwinnie 
This plugin itself is an open source project with MIT license. However, the plugin is dependent on Unity PolySpatial which requires Unity Pro license.

The [website](https://docs.unity3d.com/Packages/com.unity.polyspatial.visionos@2.0/manual/Install.html) mentions that `Developing VR or MR apps for the visionOS platform requires a Unity Pro, Enterprise, or Industrial subscription.`

I'm not sure that Unity educational license supports or not. Please try to install PolySpatial with your account with [this installation guide](https://docs.unity3d.com/Packages/com.unity.polyspatial.visionos@2.0/manual/Install.html). If your license doesn't support it, you will get an error message during the installation.

**Comment by luvwinnie** [comment]
@from2001 Thank you for clarification!

I would like to take a try with educational license.

**Comment by from2001** [comment]
@luvwinnie 
Please post the result of your try, regardless of the outcome.
Thanks.

**Comment by dfldylan** [comment]
> @from2001 Thank you for clarification!
> 
> I would like to take a try with educational license.

hey, bro , is it worked?

**Comment by from2001** [comment]
According to Unity page, Unity educational license doesn’t support PolySpatial which is required for this Enterprise camera access plugin.

Unity PolySpatial | PolySpatial | 2.0.4 
https://docs.unity3d.com/Packages/com.unity.polyspatial%402.0/manual/index.html.com
