### ISSUE TITLE
Path-through window flashes shocking pink (color of material error) when running on Vision Pro

### ISSUE THREAD

**Issue by ShutoTakashita** [styly-dev/EnterpriseCameraAccessPlugin#8]
![video (online-video-cutter com)](https://github.com/user-attachments/assets/45124e61-b4ab-4518-92ae-2a76f5562afd)

Environment
・Unity 2022.3.34f1
・Vision OS 2.0 beta
・XCode 16.1 beta

When operating in Vision Pro, the pass-through window flashes pink when switching images. This color is the color of a Unity material error.

The cause of this is in EnterpriseCameraAccessManager.cs.
In line 185, Base64ToTexture2D() creates a new Texture2D and attaches the texture to Material.mainTexture, but there is probably some delay or error when the memory reference is switched here. It would be better to LoadImage to tmpTexture.

**Comment by from2001** [comment]
Thank you for the bug report and the pull request.
It didn't happen with the older version of the visionOS 2.0 beta, and I didn't realize it.

I appreciate your contribution. I tested with Vision Pro and also Pico 4 enterprise. Your code works great. I'll merge your code and release it.

**Comment by from2001** [comment]
I just released the bug fix version of the package.
Thank you so much!

https://github.com/styly-dev/EnterpriseCameraAccessPlugin/releases/tag/v0.1.1
